/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProofRegistry } from "./ProofRegistry";
export * as factories from "./factories";
export { ProofRegistry__factory } from "./factories/ProofRegistry__factory";
