/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ProofRegistry {
  export type ProofStruct = {
    owner: AddressLike;
    ipfsHash: string;
    title: string;
    timestamp: BigNumberish;
  };

  export type ProofStructOutput = [
    owner: string,
    ipfsHash: string,
    title: string,
    timestamp: bigint
  ] & { owner: string; ipfsHash: string; title: string; timestamp: bigint };
}

export interface ProofRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createProof"
      | "getProof"
      | "getProofs"
      | "proofCount"
      | "proofs"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProofCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createProof",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProof",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getProofs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proofCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proofs",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProofs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proofCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proofs", data: BytesLike): Result;
}

export namespace ProofCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    owner: AddressLike,
    ipfsHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    owner: string,
    ipfsHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    owner: string;
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProofRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProofRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProof: TypedContractMethod<
    [title: string, ipfsHash: string],
    [bigint],
    "nonpayable"
  >;

  getProof: TypedContractMethod<
    [id: BigNumberish],
    [ProofRegistry.ProofStructOutput],
    "view"
  >;

  getProofs: TypedContractMethod<
    [],
    [ProofRegistry.ProofStructOutput[]],
    "view"
  >;

  proofCount: TypedContractMethod<[], [bigint], "view">;

  proofs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        owner: string;
        ipfsHash: string;
        title: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProof"
  ): TypedContractMethod<
    [title: string, ipfsHash: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [id: BigNumberish],
    [ProofRegistry.ProofStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProofs"
  ): TypedContractMethod<[], [ProofRegistry.ProofStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "proofCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proofs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        owner: string;
        ipfsHash: string;
        title: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ProofCreated"
  ): TypedContractEvent<
    ProofCreatedEvent.InputTuple,
    ProofCreatedEvent.OutputTuple,
    ProofCreatedEvent.OutputObject
  >;

  filters: {
    "ProofCreated(uint256,address,string,uint256)": TypedContractEvent<
      ProofCreatedEvent.InputTuple,
      ProofCreatedEvent.OutputTuple,
      ProofCreatedEvent.OutputObject
    >;
    ProofCreated: TypedContractEvent<
      ProofCreatedEvent.InputTuple,
      ProofCreatedEvent.OutputTuple,
      ProofCreatedEvent.OutputObject
    >;
  };
}
